version: "3.8"
services:
  springboot-app:
    #container_name: spring-app
    image: springboot-app
    restart: always
    build: .
    ports:
      - 8000-8999:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306


  mysqldb:
    container_name: mysqldb
    image: mysql 
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: root


